/*
 *  Arstro Artboard — aggregate header. Include this to use the platform-free core.
 *  Adapters (e.g. src/adapter/web/Canvas2DTarget.h) are included by the platform
 *  build, not here.
 */
#pragma once
#include "../../src/core/Geometry.h"
#include "../../src/core/Color.h"
#include "../../src/anim/Easing.h"
#include "../../src/anim/Animation.h"
#include "../../src/anim/Animator.h"
#include "../../src/anim/Motion.h"
#include "../../src/anim/Spring.h"
#include "../../src/render/RenderTarget.h"
#include "../../src/render/RecordingTarget.h"
#include "../../src/input/Input.h"
#include "../../src/input/GestureRecognizer.h"
#include "../../src/input/InputRouter.h"
#include "../../src/scene/Drawable.h"
#include "../../src/scene/Shapes.h"
#include "../../src/scene/Artboard.h"
// ui/base — foundations + reusable visual nodes (one class per file)
#include "../../src/ui/base/Property.h"
#include "../../src/ui/base/InputController.h"
#include "../../src/ui/base/Theme.h"
#include "../../src/ui/base/Segment.h"
#include "../../src/ui/base/AbstractSlider.h"
#include "../../src/ui/base/ModBus.h"
#include "../../src/ui/base/RectangleSegment.h"
#include "../../src/ui/base/CircleSegment.h"
#include "../../src/ui/base/LabelSegment.h"
#include "../../src/ui/base/LinearLayout.h"
#include "../../src/ui/concrete/Row.h"
#include "../../src/ui/concrete/Column.h"
// ui/concrete — the finished controls + widgets (one class per file)
#include "../../src/ui/concrete/Button.h"
#include "../../src/ui/concrete/Slider.h"
#include "../../src/ui/concrete/Checkbox.h"
#include "../../src/ui/concrete/TextBox.h"
#include "../../src/ui/concrete/Knob.h"
#include "../../src/ui/concrete/ToggleSwitch.h"
#include "../../src/ui/concrete/ProgressBar.h"
#include "../../src/ui/concrete/ComboBox.h"
#include "../../src/ui/concrete/TabView.h"
#include "../../src/ui/concrete/ScrollView.h"
#include "../../src/ui/concrete/LineGraph.h"
#include "../../src/ui/concrete/ImageView.h"
